linters:
  rubocop:
    display_cop_names: true
files:
  ignore:
    - "bin/*"
    - "db/**"
    - "config/*"
    - "Guardfile"
    - "Rakefile"
    - "reddit/config/environments/production.rb"
    - "reddit/config/environments/test.rb"
    - "reddit/config/environments/puma.rb"
    - "reddit/config/environments/spring.rb"